// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SessionCoordinatorService.Entities;

#nullable disable

namespace SessionCoordinatorService.Migrations
{
    [DbContext(typeof(SupportDbContext))]
    [Migration("20231008203215_Teams_Active_Property")]
    partial class Teams_Active_Property
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SessionCoordinatorService.Entities.ActiveAgentSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.ToTable("ActiveAgentSessions");
                });

            modelBuilder.Entity("SessionCoordinatorService.Entities.Agent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SeniorityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SeniorityId");

                    b.HasIndex("TeamId");

                    b.ToTable("Agents");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b2d6976a-d502-4cf2-b31d-2bcc07341634"),
                            Name = "Team_A_Team_Lead",
                            SeniorityId = new Guid("cf4bb79c-6573-4a7c-a7cd-e118ead8d1fb"),
                            TeamId = new Guid("4dadd8a1-6338-46ce-b12f-e351dc8797b6")
                        },
                        new
                        {
                            Id = new Guid("8b18c73a-eb9a-483b-bcf2-fc0ac6b93907"),
                            Name = "Team_A_Mid_1",
                            SeniorityId = new Guid("ecfab3b2-9ccf-46c8-99bf-fde65ce11b3b"),
                            TeamId = new Guid("4dadd8a1-6338-46ce-b12f-e351dc8797b6")
                        },
                        new
                        {
                            Id = new Guid("fb178c45-cf2d-4d36-a938-417fc20d74b6"),
                            Name = "Team_A_Mid_2",
                            SeniorityId = new Guid("ecfab3b2-9ccf-46c8-99bf-fde65ce11b3b"),
                            TeamId = new Guid("4dadd8a1-6338-46ce-b12f-e351dc8797b6")
                        },
                        new
                        {
                            Id = new Guid("fd339b30-0a15-41d6-b9e7-b820eb410a9f"),
                            Name = "Team_A_Junior",
                            SeniorityId = new Guid("2e9ce439-53fc-49a0-a1b3-c815ad880da5"),
                            TeamId = new Guid("4dadd8a1-6338-46ce-b12f-e351dc8797b6")
                        },
                        new
                        {
                            Id = new Guid("228210f2-c097-4f5e-bc9d-0396208153c9"),
                            Name = "Team_B_Senior",
                            SeniorityId = new Guid("fba73d8b-2616-4936-82f6-d38d14a22704"),
                            TeamId = new Guid("bdef6327-20f4-4a6e-942b-9ad20eab570c")
                        },
                        new
                        {
                            Id = new Guid("d1f7fc52-f847-4ceb-b044-ae826f3a5cf9"),
                            Name = "Team_B_Mid",
                            SeniorityId = new Guid("ecfab3b2-9ccf-46c8-99bf-fde65ce11b3b"),
                            TeamId = new Guid("bdef6327-20f4-4a6e-942b-9ad20eab570c")
                        },
                        new
                        {
                            Id = new Guid("e9c3e939-cff5-45e4-9e77-c68bd0dda4c0"),
                            Name = "Team_B_Junior_1",
                            SeniorityId = new Guid("2e9ce439-53fc-49a0-a1b3-c815ad880da5"),
                            TeamId = new Guid("bdef6327-20f4-4a6e-942b-9ad20eab570c")
                        },
                        new
                        {
                            Id = new Guid("7680aeb8-1768-4abb-9bef-754f50f4f809"),
                            Name = "Team_B_Junior_2",
                            SeniorityId = new Guid("2e9ce439-53fc-49a0-a1b3-c815ad880da5"),
                            TeamId = new Guid("bdef6327-20f4-4a6e-942b-9ad20eab570c")
                        },
                        new
                        {
                            Id = new Guid("9e0174c2-bd45-4659-b56c-1841464ddb1e"),
                            Name = "Team_C_Mid_1",
                            SeniorityId = new Guid("ecfab3b2-9ccf-46c8-99bf-fde65ce11b3b"),
                            TeamId = new Guid("5a2074de-281f-4baf-879d-e58ec75a6c42")
                        },
                        new
                        {
                            Id = new Guid("9524efba-f611-4382-9398-5708c7e71888"),
                            Name = "Team_C_Mid_2",
                            SeniorityId = new Guid("ecfab3b2-9ccf-46c8-99bf-fde65ce11b3b"),
                            TeamId = new Guid("5a2074de-281f-4baf-879d-e58ec75a6c42")
                        },
                        new
                        {
                            Id = new Guid("ea122361-89b8-4d30-8bee-108539c2f5ff"),
                            Name = "Team_Overflow_Junior_1",
                            SeniorityId = new Guid("2e9ce439-53fc-49a0-a1b3-c815ad880da5"),
                            TeamId = new Guid("9f6d40f5-7031-4c10-ab54-b940d217a99f")
                        },
                        new
                        {
                            Id = new Guid("511d122e-4ce2-463a-a58c-127e6d98838d"),
                            Name = "Team_Overflow_Junior_2",
                            SeniorityId = new Guid("2e9ce439-53fc-49a0-a1b3-c815ad880da5"),
                            TeamId = new Guid("9f6d40f5-7031-4c10-ab54-b940d217a99f")
                        },
                        new
                        {
                            Id = new Guid("93b7c28d-4e86-43a0-9487-1bf57a1b2271"),
                            Name = "Team_Overflow_Junior_3",
                            SeniorityId = new Guid("2e9ce439-53fc-49a0-a1b3-c815ad880da5"),
                            TeamId = new Guid("9f6d40f5-7031-4c10-ab54-b940d217a99f")
                        },
                        new
                        {
                            Id = new Guid("63c91c31-50ee-4c9c-8c2f-526889b49dff"),
                            Name = "Team_Overflow_Junior_4",
                            SeniorityId = new Guid("2e9ce439-53fc-49a0-a1b3-c815ad880da5"),
                            TeamId = new Guid("9f6d40f5-7031-4c10-ab54-b940d217a99f")
                        },
                        new
                        {
                            Id = new Guid("6f8a832c-bb78-4493-8ea8-d5d5807e2b76"),
                            Name = "Team_Overflow_Junior_5",
                            SeniorityId = new Guid("2e9ce439-53fc-49a0-a1b3-c815ad880da5"),
                            TeamId = new Guid("9f6d40f5-7031-4c10-ab54-b940d217a99f")
                        },
                        new
                        {
                            Id = new Guid("cbafae8d-2226-4151-b68b-045b1badd74d"),
                            Name = "Team_Overflow_Junior_6",
                            SeniorityId = new Guid("2e9ce439-53fc-49a0-a1b3-c815ad880da5"),
                            TeamId = new Guid("9f6d40f5-7031-4c10-ab54-b940d217a99f")
                        });
                });

            modelBuilder.Entity("SessionCoordinatorService.Entities.AgentSeniority", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("SeniorityMultiplier")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Seniority");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2e9ce439-53fc-49a0-a1b3-c815ad880da5"),
                            Name = "Junior",
                            Priority = 1,
                            SeniorityMultiplier = 4
                        },
                        new
                        {
                            Id = new Guid("ecfab3b2-9ccf-46c8-99bf-fde65ce11b3b"),
                            Name = "Mid-Level",
                            Priority = 2,
                            SeniorityMultiplier = 6
                        },
                        new
                        {
                            Id = new Guid("fba73d8b-2616-4936-82f6-d38d14a22704"),
                            Name = "Senior",
                            Priority = 3,
                            SeniorityMultiplier = 8
                        },
                        new
                        {
                            Id = new Guid("cf4bb79c-6573-4a7c-a7cd-e118ead8d1fb"),
                            Name = "Team Lead",
                            Priority = 4,
                            SeniorityMultiplier = 5
                        });
                });

            modelBuilder.Entity("SessionCoordinatorService.Entities.SessionMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MessageBody")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SentBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.ToTable("SessionChats");
                });

            modelBuilder.Entity("SessionCoordinatorService.Entities.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WorkFinishHourAt")
                        .HasColumnType("int");

                    b.Property<int>("WorkStartHourAt")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4dadd8a1-6338-46ce-b12f-e351dc8797b6"),
                            Active = true,
                            Name = "A",
                            WorkFinishHourAt = 18,
                            WorkStartHourAt = 10
                        },
                        new
                        {
                            Id = new Guid("bdef6327-20f4-4a6e-942b-9ad20eab570c"),
                            Active = true,
                            Name = "B",
                            WorkFinishHourAt = 2,
                            WorkStartHourAt = 18
                        },
                        new
                        {
                            Id = new Guid("5a2074de-281f-4baf-879d-e58ec75a6c42"),
                            Active = true,
                            Name = "C",
                            WorkFinishHourAt = 10,
                            WorkStartHourAt = 2
                        },
                        new
                        {
                            Id = new Guid("9f6d40f5-7031-4c10-ab54-b940d217a99f"),
                            Active = false,
                            Name = "Overflow",
                            WorkFinishHourAt = 18,
                            WorkStartHourAt = 10
                        });
                });

            modelBuilder.Entity("SessionCoordinatorService.Entities.ActiveAgentSession", b =>
                {
                    b.HasOne("SessionCoordinatorService.Entities.Agent", "Agent")
                        .WithMany("ActiveAgentSessions")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("SessionCoordinatorService.Entities.Agent", b =>
                {
                    b.HasOne("SessionCoordinatorService.Entities.AgentSeniority", "Seniority")
                        .WithMany("Agents")
                        .HasForeignKey("SeniorityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SessionCoordinatorService.Entities.Team", "Team")
                        .WithMany("Agents")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Seniority");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("SessionCoordinatorService.Entities.SessionMessage", b =>
                {
                    b.HasOne("SessionCoordinatorService.Entities.Agent", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("SessionCoordinatorService.Entities.Agent", b =>
                {
                    b.Navigation("ActiveAgentSessions");
                });

            modelBuilder.Entity("SessionCoordinatorService.Entities.AgentSeniority", b =>
                {
                    b.Navigation("Agents");
                });

            modelBuilder.Entity("SessionCoordinatorService.Entities.Team", b =>
                {
                    b.Navigation("Agents");
                });
#pragma warning restore 612, 618
        }
    }
}
