// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SessionCoordinatorService.Entities;

#nullable disable

namespace SessionCoordinatorService.Migrations
{
    [DbContext(typeof(SupportDbContext))]
    partial class SupportDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SessionCoordinatorService.Entities.ActiveAgentSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.ToTable("ActiveAgentSessions");
                });

            modelBuilder.Entity("SessionCoordinatorService.Entities.Agent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SeniorityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SeniorityId");

                    b.HasIndex("TeamId");

                    b.ToTable("Agents");

                    b.HasData(
                        new
                        {
                            Id = new Guid("011120b1-deb1-4a25-a722-07b0c3cc619f"),
                            Name = "Team_A_Team_Lead",
                            SeniorityId = new Guid("70e14af8-2b36-491a-9fe7-f041e6f8548d"),
                            TeamId = new Guid("28fbf6fe-1a4a-4304-b88d-acd03e273014")
                        },
                        new
                        {
                            Id = new Guid("10fbdf23-ddb3-4547-b015-54c5e19fa0b6"),
                            Name = "Team_A_Mid_1",
                            SeniorityId = new Guid("95d957dc-7184-4506-b4f8-f0eca3d4d9f5"),
                            TeamId = new Guid("28fbf6fe-1a4a-4304-b88d-acd03e273014")
                        },
                        new
                        {
                            Id = new Guid("9ce592e4-7de9-4121-9164-78a068659a76"),
                            Name = "Team_A_Mid_2",
                            SeniorityId = new Guid("95d957dc-7184-4506-b4f8-f0eca3d4d9f5"),
                            TeamId = new Guid("28fbf6fe-1a4a-4304-b88d-acd03e273014")
                        },
                        new
                        {
                            Id = new Guid("8ae34fde-fab5-4e06-8483-48801321dc14"),
                            Name = "Team_A_Junior",
                            SeniorityId = new Guid("693322d7-1989-4e35-8449-50d7262be52c"),
                            TeamId = new Guid("28fbf6fe-1a4a-4304-b88d-acd03e273014")
                        },
                        new
                        {
                            Id = new Guid("75eac2fa-b183-48f2-9a85-765b266c5540"),
                            Name = "Team_B_Senior",
                            SeniorityId = new Guid("4b2b355f-c2f6-487e-b2af-58a37243218b"),
                            TeamId = new Guid("3a5aab28-b35d-40fe-bca1-e9ec849b6459")
                        },
                        new
                        {
                            Id = new Guid("3b5fdebe-e447-4bca-8e40-bf95b176a8f5"),
                            Name = "Team_B_Mid",
                            SeniorityId = new Guid("95d957dc-7184-4506-b4f8-f0eca3d4d9f5"),
                            TeamId = new Guid("3a5aab28-b35d-40fe-bca1-e9ec849b6459")
                        },
                        new
                        {
                            Id = new Guid("69cd109c-ac88-4c30-984a-10c8530c4be7"),
                            Name = "Team_B_Junior_1",
                            SeniorityId = new Guid("693322d7-1989-4e35-8449-50d7262be52c"),
                            TeamId = new Guid("3a5aab28-b35d-40fe-bca1-e9ec849b6459")
                        },
                        new
                        {
                            Id = new Guid("edf5938d-8397-404f-abf4-377e51607707"),
                            Name = "Team_B_Junior_2",
                            SeniorityId = new Guid("693322d7-1989-4e35-8449-50d7262be52c"),
                            TeamId = new Guid("3a5aab28-b35d-40fe-bca1-e9ec849b6459")
                        },
                        new
                        {
                            Id = new Guid("6d16410a-19a9-4298-9f1c-f9455a214d0e"),
                            Name = "Team_C_Mid_1",
                            SeniorityId = new Guid("95d957dc-7184-4506-b4f8-f0eca3d4d9f5"),
                            TeamId = new Guid("e8120c31-461b-4a93-8f61-9e37dbf5a8cb")
                        },
                        new
                        {
                            Id = new Guid("933a6450-49b8-47a7-83ee-2a66cd175335"),
                            Name = "Team_C_Mid_2",
                            SeniorityId = new Guid("95d957dc-7184-4506-b4f8-f0eca3d4d9f5"),
                            TeamId = new Guid("e8120c31-461b-4a93-8f61-9e37dbf5a8cb")
                        },
                        new
                        {
                            Id = new Guid("42fad6d9-49a6-4d74-a1f1-6741de0273ed"),
                            Name = "Team_Overflow_Junior_1",
                            SeniorityId = new Guid("693322d7-1989-4e35-8449-50d7262be52c"),
                            TeamId = new Guid("6e9be61e-0bb7-42b7-8462-bb45f8fab017")
                        },
                        new
                        {
                            Id = new Guid("6ec60c06-c978-42a4-8c4f-3c10cd5d4f22"),
                            Name = "Team_Overflow_Junior_2",
                            SeniorityId = new Guid("693322d7-1989-4e35-8449-50d7262be52c"),
                            TeamId = new Guid("6e9be61e-0bb7-42b7-8462-bb45f8fab017")
                        },
                        new
                        {
                            Id = new Guid("68c30ca4-2d2e-4e08-a576-b2c0ba1bd599"),
                            Name = "Team_Overflow_Junior_3",
                            SeniorityId = new Guid("693322d7-1989-4e35-8449-50d7262be52c"),
                            TeamId = new Guid("6e9be61e-0bb7-42b7-8462-bb45f8fab017")
                        },
                        new
                        {
                            Id = new Guid("4392a336-2598-4ee2-a14c-19e0486d3fdd"),
                            Name = "Team_Overflow_Junior_4",
                            SeniorityId = new Guid("693322d7-1989-4e35-8449-50d7262be52c"),
                            TeamId = new Guid("6e9be61e-0bb7-42b7-8462-bb45f8fab017")
                        },
                        new
                        {
                            Id = new Guid("27356d94-050d-449d-81ef-2bf501abc3e3"),
                            Name = "Team_Overflow_Junior_5",
                            SeniorityId = new Guid("693322d7-1989-4e35-8449-50d7262be52c"),
                            TeamId = new Guid("6e9be61e-0bb7-42b7-8462-bb45f8fab017")
                        },
                        new
                        {
                            Id = new Guid("c0acd479-7239-45f6-ae01-5d8a467499f0"),
                            Name = "Team_Overflow_Junior_6",
                            SeniorityId = new Guid("693322d7-1989-4e35-8449-50d7262be52c"),
                            TeamId = new Guid("6e9be61e-0bb7-42b7-8462-bb45f8fab017")
                        });
                });

            modelBuilder.Entity("SessionCoordinatorService.Entities.AgentSeniority", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SeniorityMultiplier")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Seniority");

                    b.HasData(
                        new
                        {
                            Id = new Guid("693322d7-1989-4e35-8449-50d7262be52c"),
                            Name = "Junior",
                            SeniorityMultiplier = 4
                        },
                        new
                        {
                            Id = new Guid("95d957dc-7184-4506-b4f8-f0eca3d4d9f5"),
                            Name = "Mid-Level",
                            SeniorityMultiplier = 6
                        },
                        new
                        {
                            Id = new Guid("4b2b355f-c2f6-487e-b2af-58a37243218b"),
                            Name = "Senior",
                            SeniorityMultiplier = 8
                        },
                        new
                        {
                            Id = new Guid("70e14af8-2b36-491a-9fe7-f041e6f8548d"),
                            Name = "Team Lead",
                            SeniorityMultiplier = 5
                        });
                });

            modelBuilder.Entity("SessionCoordinatorService.Entities.SessionMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MessageBody")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SentBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.ToTable("SessionChats");
                });

            modelBuilder.Entity("SessionCoordinatorService.Entities.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WorkFinishHourAt")
                        .HasColumnType("int");

                    b.Property<int>("WorkStartHourAt")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = new Guid("28fbf6fe-1a4a-4304-b88d-acd03e273014"),
                            Name = "A",
                            WorkFinishHourAt = 18,
                            WorkStartHourAt = 10
                        },
                        new
                        {
                            Id = new Guid("3a5aab28-b35d-40fe-bca1-e9ec849b6459"),
                            Name = "B",
                            WorkFinishHourAt = 2,
                            WorkStartHourAt = 18
                        },
                        new
                        {
                            Id = new Guid("e8120c31-461b-4a93-8f61-9e37dbf5a8cb"),
                            Name = "C",
                            WorkFinishHourAt = 10,
                            WorkStartHourAt = 2
                        },
                        new
                        {
                            Id = new Guid("6e9be61e-0bb7-42b7-8462-bb45f8fab017"),
                            Name = "Overflow",
                            WorkFinishHourAt = 18,
                            WorkStartHourAt = 10
                        });
                });

            modelBuilder.Entity("SessionCoordinatorService.Entities.ActiveAgentSession", b =>
                {
                    b.HasOne("SessionCoordinatorService.Entities.Agent", "Agent")
                        .WithMany("ActiveAgentSessions")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("SessionCoordinatorService.Entities.Agent", b =>
                {
                    b.HasOne("SessionCoordinatorService.Entities.AgentSeniority", "Seniority")
                        .WithMany("Agents")
                        .HasForeignKey("SeniorityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SessionCoordinatorService.Entities.Team", "Team")
                        .WithMany("Agents")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Seniority");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("SessionCoordinatorService.Entities.SessionMessage", b =>
                {
                    b.HasOne("SessionCoordinatorService.Entities.Agent", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("SessionCoordinatorService.Entities.Agent", b =>
                {
                    b.Navigation("ActiveAgentSessions");
                });

            modelBuilder.Entity("SessionCoordinatorService.Entities.AgentSeniority", b =>
                {
                    b.Navigation("Agents");
                });

            modelBuilder.Entity("SessionCoordinatorService.Entities.Team", b =>
                {
                    b.Navigation("Agents");
                });
#pragma warning restore 612, 618
        }
    }
}
